pipeline {
    agent any
    environment {
        AWS_REGION = 'ap-south-1'
        ECR_REPO = 'your-ecr-repo'
        IMAGE_TAG = 'latest'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("your-image-name")
                }
            }
        }
        stage('Push to ECR') {
            steps {
                script {
                    sh '$(aws ecr get-login --no-include-email --region ap-south-1)'
                    docker.image("your-image-name").push("latest")
                }
            }
        }
        stage('Deploy to EKS') {
            steps {
                script {
                    kubectl.apply('-f k8s-deployment.yaml')
                    kubectl.apply('-f k8s-service.yaml')
                }
            }
        }
    }
}
