pipeline {
    agent any
    environment {
        AWS_REGION = 'ap-south-1'
        ECR_REPO = 'your-ecr-repo'
        IMAGE_TAG = 'latest'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("your-image-name")
                }
            }
        }
        stage('Push to ECR') {
            steps {
                script {
                    // Login to ECR
                    def ecrLoginCommand = 'aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin 014498666580.dkr.ecr.ap-south-1.amazonaws.com '
                    sh ecrLoginCommand

                    // Push the Docker image to ECR
                    docker.image("your-image-name").push("${IMAGE_TAG}")
                }
            }
        }
        stage('Deploy to EKS') {
            steps {
                script {
                    // Apply Kubernetes configurations
                    sh 'kubectl apply -f k8s-deployment.yaml'
                    sh 'kubectl apply -f k8s-service.yaml'
                }
            }
        }
    }
}


